[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bisection-method"
version = "0.1.0"
description = "A simple implementation of the bisection method"
dependencies = []
