name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.12.8"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Install test dependencies
        run: pip install numpy pytest pytest-cov

      # - name: Install Bisection package
      #   run: pip install -e ./bisection
        
      - name: Install Newton package
        run: pip install -e ./newton


      - name: Install ElastoplasticModel package
        run: pip install -e ./ElastoplasticModel

      - name: Run tests with coverage
        run: |
          pytest --cov=newton --cov-report=xml
          pytest --cov=ElastoplasticModel --cov-report=xml
  # pytest --cov=bisection --cov-report=xml
  
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
